data:
  raw_file: data/raw_data/raw.csv

split:
  test_size: 0.2
  random_state: 42
  stratify: false

preprocessing:
  numerical:
    strategy: "standard"  # Options: standard, minmax, robust

models:
  - name: "RandomForest"
    params:
      n_estimators: [50, 100]
      max_depth: [10, 20, null]
      min_samples_split: [2, 5]
      
  - name: "GradientBoosting"
    params:
      n_estimators: [50, 100]
      learning_rate: [0.05, 0.1]
      max_depth: [3, 5]

grid_search:
  cv: 3
  scoring: "neg_mean_squared_error"
  n_jobs: -1
  verbose: 1

evaluation:
  metrics:
    - "mse"
    - "rmse"
    - "mae"
    - "r2"
    - "mape"
